apiVersion: apps/v1
kind: Deployment
metadata:
  name: balie-server
  labels:
    {{- include "irmaBalie.labels" $ | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: balie-server
  template:
    metadata:
      labels:
        app: balie-server
    spec:
      containers:
        - name: balie-server
          image: {{$.Values.imageBalieServer}}
          imagePullPolicy: IfNotPresent
          env:
            - name: BALIE_SERVER_DEBUGMODE
              value: "{{$.Values.balieServer.debugMode}}"
            - name: BALIE_SERVER_LISTENADDRESS
              value: ":8080"
            - name: BALIE_SERVER_IRMASERVER
              value: http://irma-server-internal
            - name: BALIE_SERVER_JWTSECRET
              value: 2eEaV5z1oNQMqxobuvTrkAo
            - name: BALIE_SERVER_PASSPORTCREDENTIALID
              value: "pbdf.pilot-amsterdam.passport"
            - name: BALIE_SERVER_IDCARDCREDENTIALID
              value: "pbdf.pilot-amsterdam.idcard"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 1
      imagePullSecrets:
      - name: github-registry
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: balie-server
spec:
  type: ClusterIP
  selector:
    app: balie-server
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: balie-server
spec:
  secretName: tls-cert-balie-server
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod-http
  dnsNames:
    - balie-server.{{ $.Values.env }}.company.gcp.stack11.net

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: balie-server
spec:
  parentRefs:
    - name: yivi-gateway
      namespace: yivi-balie
  hostnames:
    - balie-server.{{ $.Values.env }}.company.gcp.stack11.net
  rules:
    - backendRefs:
      - name: balie-server
        port: 80
