apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yivi-server-jwt
spec:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: yivi-server-jwt
  data:
    - secretKey: jwt_privkey
      remoteRef:
        property: jwt_privkey
        key: yivi-balie-server-jwt
---

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: yivi-server-pilot-amsterdam-privkeys
spec:
  secretStoreRef:
    name: openbao
    kind: ClusterSecretStore
  target:
    name: yivi-server-pilot-amsterdam-privkeys
  data:
    - secretKey: "0.xml"
      remoteRef:
        property: "0.xml"
        key: "yivi-server-pilot-amsterdam-privkeys"
    - secretKey: "1.xml"
      remoteRef:
        property: "1.xml"
        key: "yivi-server-pilot-amsterdam-privkeys"
    - secretKey: "2.xml"
      remoteRef:
        property: "2.xml"
        key: "yivi-server-pilot-amsterdam-privkeys"
    - secretKey: "3.xml"
      remoteRef:
        property: "3.xml"
        key: "yivi-server-pilot-amsterdam-privkeys"
